name: Release Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    # https://github.com/actions/runner-images/blob/main/images/windows/Windows2025-Readme.md
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v5
    
    - name: Check formatting
      run: cargo fmt --check

    - name: Run Tests
      run: cargo test

    - name: Create distribution
      run: cargo xtask dist

    - name: Archive
      uses: vimtor/action-zip@v1
      with:
        files: dist/
        dest: xplane-uipc.zip
        recursive: true

    - name: Release
      uses: softprops/action-gh-release@v3
      with:
        fail_on_unmatched_files: true
        files: |
          xplane-uipc.zip
